// src/routes/components/Introduction.svelte
<div class="introduction-container">
  <img src="me.jpg" alt="" class="rounded_img profile-photo" />
  <div>
    <div class="name">
      <p>Welcome. I am <strong>Efe Murat Rendeci</strong></p>
    </div>
    <p class="short_info">
      I am a dedicated Full Stack Developer with a passion for crafting robust backend solutions and creating solutions for the existing system architectures. Love coding and self improvement.
    </p>
  </div>
</div>

// src/components/Introduction.jsx
export default function Introduction() {
  return (
    <div className="introduction-container">
      <img src="/me.jpg" alt="" className="rounded_img profile-photo" />
      <div>
        <div className="name">
          <p>
            Welcome. I am <strong>Efe Murat Rendeci</strong>
          </p>
        </div>
        <p className="short_info">
          I am a dedicated Full Stack Developer with a passion for crafting
          robust backend solutions and creating solutions for the existing
          system architectures. Love coding and self improvement.
        </p>
      </div>
    </div>
  );
}
